### ISSUE TITLE
DPLSTM Memory Footprint

### ISSUE THREAD

**Issue by pranavsubramani** [pytorch/opacus#53]
I was recently running a sample network on the IMDB dataset. The network is defined below:

```

class SampleNet(nn.Module):
    def __init__(self, vocab_size: int, batch_size):
        super(SampleNet, self).__init__()
        # Embedding dimension: vocab_size + <unk>, <pad>, <eos>, <sos>
        self.emb = nn.Embedding(vocab_size + 4, 100)
        self.h_init = torch.randn(1, batch_size, 100).to(device)
        self.c_init = torch.randn(1, batch_size, 100).to(device)
        self.hidden = (self.h_init, self.c_init)
        self.lstm = DPLSTM(100, 100, batch_first = True)
        self.pool = nn.AvgPool1d(256)
        self.fc1 = nn.Linear(100, 2)

    def forward(self, x):
        x = self.emb(x)
        x, _ = self.lstm(x, self.hidden)
        x = x.transpose(1,2)
        x = self.pool(x).squeeze()

        x = self.fc1(x)
        return x

```

Some notes on the code, the vocab_size is 10_000, the batch size is 100. When I run this code, torch gives me an out of memory error saying the following:

`RuntimeError: CUDA out of memory. Tried to allocate 95.41 GiB (GPU 0; 3.95 GiB total capacity; 2.18 GiB already allocated; 369.06 MiB free; 2.21 GiB reserved in total by PyTorch)
`

Note that when I use the regular `torch.nn.LSTM` -- this error does not occur. I'm curious of why the memory footprint is extremely large for the DPLSTM implementation and could it possibly be because I am doing something wrong?

EDIT: This also only happens in the backward pass.

**Comment by karthikprasad** [comment]
Hello @pranavsubramani , backward pass with DP-SGD does occupy more memory than a regular SGD primarily because of the the need to maintain gradients of parameters for every input data point. Bigger batch => more datapoints => more gradient copies.
Please checkout the FAQ section https://opacus.ai/docs/faq#how-to-deal-with-out-of-memory-errors on this topic, it suggests some of the steps you can try to overcome this issue.

**Comment by pranavsubramani** [comment]
Thanks for the reference, I'm going to go ahead and close the issue because I managed to fix it!

**Comment by birdx0810** [comment]
@pranavsubramani Hi, I'm currently facing similar issues, could I ask how did you manage to fix your problem?

**Comment by jasonkena** [comment]
@birdx0810 I faced a similar problem when I was using `GradSampleModule`. The problem was that I needed to call the overloaded `model.zero_grad()` instead of `optim.zero_grad()` to clear the accumulated `grad_sample` attributes.
